// GRBL dialect. No tool changer (comment only), no canned cycles (the core
// expands drills long-hand), no G43 tool length compensation.

import { num, spindleWord } from './format.js';

export const grbl = {
  name: 'GRBL',
  arcs: true,      // grbl takes G2/G3 I/J and expands them itself

  header(w, { programName = 'CNCAM' } = {}) {
    w.comment(programName);
    w.comment(`generated by CNCAM ${new Date().toISOString().slice(0, 10)} — GRBL post`);
    w.line('G21 G90 G94 G17');
  },

  /**
   * GRBL has no tool changer, so a change is the operator's job — and the
   * program has to stop for them to do it.
   *
   * It used to write only a comment. A comment does not stop anything: the
   * controller read the next block and carried on cutting the second
   * operation with the first operation's cutter, which on a program that goes
   * from a ⌀12 rougher to a ⌀3 finisher is a broken tool and on the reverse a
   * gouged part. M0 is the program-stop every GRBL build honours and every
   * sender offers a resume button for.
   *
   * A machine that really does have a changer says so on its record, and then
   * this writes the change instead of asking for it.
   */
  toolChange(w, modal, { tool }, options = {}) {
    if (options.toolChanger === 'auto') {
      w.line(`T${tool} M6`);
      modal.reset();   // controller state after a change is not ours to assume
      return;
    }
    w.comment(`fit tool T${tool} — press cycle start to go on`);
    w.line('M0');
  },

  spindle(w, { rpm, dir }) {
    w.line(`${spindleWord(dir)} S${Math.round(rpm)}`);
  },

  drill: null, // expanded long-hand by the core

  // Out of the cut before the spindle stops — see post/linuxcnc.js. The retract
  // goes through the modal tracker so it is not the second one in a row.
  footer(w, { safeZ, spindleOn, modal }) {
    const z = modal ? modal.word('Z', safeZ) : `Z${num(safeZ)}`;
    if (z) w.line('G0', z);
    if (spindleOn) w.line('M5');
    w.line('M2');
  },
};
