// Lathe dialect (LinuxCNC lathe mode).
//
// Three things make a lathe post different from a mill post, and all three are
// ways to cut a part to the wrong size:
//
//   X is a **diameter**. CL data holds a radius, because that is the geometry,
//   so it is doubled exactly here and nowhere else. `G7` tells the control the
//   X words that follow are diameters; without it the same numbers mean radii
//   and every feature comes out twice as deep as it was asked for.
//
//   There is no Y. A Y word on a lathe is at best ignored and at worst an
//   error, so the motion writer simply does not emit one.
//
//   A feed is per **revolution**, not per minute. That is not a formatting
//   preference: it is what makes the chip the same thickness at every diameter,
//   and it is why a lathe insert's catalogue figure is quoted in mm/rev. G95
//   turns it on; the feeds CNCAM holds are mm/min, so they are divided by the
//   spindle speed on the way out — in one place, here.
//
// Threading is spindle-synchronised motion (G33), not a G1 at a cleverly chosen
// feed. The carriage has to be locked to the encoder or every pass after the
// first starts a little further round the bar and the form is destroyed. The
// strategy marks the pass (`cl.threadPass`) and this writes it.
//
// Arcs are off: the fitter in post/arcs.js works in XY and a lathe's arcs are
// in ZX (G18). Fitting them is a real thing to do later; emitting XY arc
// centres into a ZX plane is not.

import { num, spindleWord } from './format.js';

export const lathe = {
  name: 'Lathe (LinuxCNC)',
  arcs: false,
  lathe: true,      // the app uses this to offer turning strategies
  synchronised: true,   // it can write G33, so threading is real threading

  header(w, { programName = 'CNCAM', feedMode = 'perRev', machine = null } = {}) {
    w.comment(programName);
    w.comment(`generated by CNCAM ${new Date().toISOString().slice(0, 10)} — lathe post`);
    if (machine) w.comment(`machine: ${machine}`);
    w.comment('X words are diameters (G7); Z runs along the spindle');
    const feedWord = feedMode === 'perMinute' ? 'G94' : 'G95';
    w.comment(feedMode === 'perMinute'
      ? 'feed is mm/min (G94)'
      : 'feed is mm/rev (G95) — the figure on the insert box');
    // G18: the ZX plane, which is the one a lathe works in.
    // G7:  diameter mode.
    w.line(`G21 G90 ${feedWord} G18 G7 G40 G49 G80`);
  },

  /**
   * A move on a lathe: X as a diameter, Z along the bar, and no Y at all.
   *
   * The modal tracker is fed the doubled value, so "unchanged" means unchanged
   * in the units actually written — a radius that moves by 0.001 and a diameter
   * that moves by 0.002 are the same event, and only one of them is a word.
   */
  motion(w, modal, { rapid, x, z, feed, threadPitch = 0, rpm = 0, feedMode = 'perRev' }) {
    const wx = modal.word('X', x * 2);
    const wz = modal.word('Z', z);
    if (!wx && !wz) return;
    if (rapid) return w.line(modal.word('G', 0, 0), wx, wz);
    if (threadPitch > 0) {
      // G33 X- Z- K-: synchronised straight motion, K millimetres of travel per
      // spindle revolution. No F: the feed *is* the pitch.
      return w.line(modal.word('G', 33, 0), wx, wz, `K${num(threadPitch, 4)}`);
    }
    return w.line(modal.word('G', 1, 0), wx, wz,
      modal.word('F', latheFeed(feed, rpm, feedMode), feedMode === 'perMinute' ? 1 : 4));
  },

  toolChange(w, modal, { tool }) {
    // T0101: turret station 1, offset 1. The pairing is the lathe convention
    // and every control that reads this file will expect it.
    const station = String(tool).padStart(2, '0');
    w.line(`T${station}${station} M6`);
    modal.reset();   // the turret has moved; nothing modal survives it
  },

  /**
   * G97 holds an rpm; G96 holds a *surface speed* and lets the control work the
   * rpm out from the diameter it is at.
   *
   * G96 is what a lathe is for. Facing at a fixed rpm means the surface speed
   * falls to nothing at the centre, so the last few millimetres are cut by an
   * insert that is rubbing rather than cutting — which is what burnishes the
   * middle of a faced end and takes the corner off the insert. It needs a
   * maximum rpm with it, always: as the tool reaches the axis the commanded
   * speed goes to infinity, and the clamp is the only thing between that and an
   * unbalanced bar at the top of the spindle's range.
   */
  spindle(w, { rpm, dir, mode, surfaceSpeed, maxRpm }) {
    const turn = spindleWord(dir);
    if (mode === 'css' && surfaceSpeed > 0) {
      const clamp = maxRpm > 0 ? maxRpm : Math.max(200, Math.round(rpm || 2000));
      w.line(`G96 D${Math.round(clamp)} S${Math.round(surfaceSpeed)} ${turn}`);
      w.comment(`constant surface speed ${Math.round(surfaceSpeed)} m/min, capped at ${Math.round(clamp)} rpm`);
      return;
    }
    w.line(`G97 S${Math.round(rpm)} ${turn}`);
  },

  // No canned cycles: a centre drill on a lathe posts as plain moves down the
  // axis, which the core already expands, and G81 in lathe mode is a G-code
  // minefield across controls.
  drill: null,

  footer(w, { safeX, spindleOn, modal }) {
    // Cross-slide clear of the work first: a parting blade left in the groove
    // when the spindle stops is a blade the operator has to free by hand, and
    // anything still touching the bar gets a witness mark as it runs down.
    // Through the modal tracker, so a pass that already retracted there does not
    // say it twice — X is a diameter here, as everywhere else in this file.
    const diameter = Math.max(safeX * 2, 0);
    const x = modal ? modal.word('X', diameter) : `X${num(diameter)}`;
    if (x) w.line('G0', x);
    // Then G97, because leaving the control in constant-surface-speed mode
    // means the next thing anybody types at the MDI runs at a speed set by
    // wherever the tool happens to be sitting.
    w.line('G97');
    if (spindleOn) w.line('M5');
    w.line('M2');
  },
};

/**
 * The feed as the control will read it.
 *
 * mm/min ÷ rpm is mm/rev. With no spindle speed to divide by there is no honest
 * conversion, so the mm/min figure is passed through rather than a made-up one
 * written — a program with no S word in it has bigger problems than its units.
 */
export function latheFeed(feedPerMin, rpm, feedMode) {
  if (feedMode === 'perMinute' || !(rpm > 0)) return feedPerMin;
  return feedPerMin / rpm;
}
