// LinuxCNC (rs274ngc) dialect. Tool changes (T..M6 + G43), canned drill
// cycles (G98 G81/G83, G80 cancel), full safety header.

import { num, spindleWord } from './format.js';

export const linuxcnc = {
  name: 'LinuxCNC',
  arcs: true,      // G2/G3 with I/J, in the G17 plane the header selects

  header(w, { programName = 'CNCAM' } = {}) {
    w.comment(programName);
    w.comment(`generated by CNCAM ${new Date().toISOString().slice(0, 10)} — LinuxCNC post`);
    // G91.1: arc centres are offsets from the arc start, which is what the post
    // emits and what every controller it targets defaults to — stated anyway,
    // because the one machine that does not would cut a circle of its own choosing
    w.line('G21 G90 G94 G17 G40 G49 G80 G91.1');
  },

  toolChange(w, modal, { tool }) {
    w.line(`T${tool} M6`);
    w.line(`G43 H${tool}`);
    modal.reset(); // controller state after M6 is not ours to assume
  },

  spindle(w, { rpm, dir }) {
    w.line(`${spindleWord(dir)} S${Math.round(rpm)}`);
  },

  // Indexed 3+1 / 3+2: a tilted work plane. G68.2 declares the plane by the
  // same XYZ Euler angles the CAM turned the mesh through (see engine/indexing.js),
  // and G53.1 swings the rotary axes so the spindle stands normal to it. From
  // there the operation's own X/Y/Z are read in the tilted frame — which is why
  // the strategies need no idea any of this happened. G69 cancels it.
  tiltedPlane: {
    set(w, modal, orientation) {
      const [i, j, k] = orientation.euler;
      const ang = orientation.angles ?? {};
      const swing = Object.keys(ang).length
        ? Object.entries(ang).map(([letter, deg]) => `${letter}${num(deg)}`).join(' ')
        : 'the rotary axes';
      w.comment(`index ${orientation.kind}: tool axis `
        + `${orientation.toolAxis.map((v) => num(v, 3)).join(' ')} — ${swing}`);
      w.line(`G68.2 X0 Y0 Z0 I${num(i)} J${num(j)} K${num(k)}`);
      w.line('G53.1');   // orient the tool normal to the plane
      modal.reset();     // coordinates are in the tilted frame now
    },
    cancel(w, modal) {
      w.line('G69');
      modal.reset();
    },
  },

  drill: {
    // rs274ngc's G83 takes Q and no P — there is nowhere to put a dwell — so a
    // hole given both gets the peck and the core writes the reason the dwell is
    // missing. A dialect whose peck cycle does carry one sets this true.
    dwellWithPeck: false,

    start(w, m, feeds) {
      // peck wins over dwell: G83 already lifts to clear chips, and a pause at
      // the bottom of a pecked hole is not what the dwell was asked for
      const cycle = m.peck > 0 ? 'G83' : m.dwell > 0 ? 'G82' : 'G81';
      const extra = m.peck > 0 ? ` Q${num(m.peck)}`
        : m.dwell > 0 ? ` P${num(m.dwell, 2)}` : '';
      w.line(`G98 ${cycle} X${num(m.x)} Y${num(m.y)} Z${num(m.z)} R${num(m.retractZ)}${extra} F${num(feeds.plunge, 1)}`);
    },
    next(w, m) {
      w.line(`X${num(m.x)} Y${num(m.y)}`);
    },
    cancel(w) {
      w.line('G80');
    },
  },

  // Retract, *then* stop the spindle. The other order pulls a stationary cutter
  // out of whatever it is in, which is how an end mill gets snapped and a
  // finished bore gets a witness mark down it. Every operation happens to end at
  // clearance today, so this costs nothing and is the only order that is safe
  // when one does not.
  footer(w, { safeZ, spindleOn, modal }) {
    // Asked of the modal tracker rather than written flat, so the retract the
    // last operation already made is not made twice. Nothing modal survives a
    // canned cycle, so a program that ends on one still gets its retract.
    const z = modal ? modal.word('Z', safeZ) : `Z${num(safeZ)}`;
    if (z) w.line('G0', z);
    if (spindleOn) w.line('M5');
    w.line('M2');
  },
};
